### PR TITLE
Update team members

### PR DESCRIPTION
**Pull request by jasontsh**
Update years and remove old members

### CODE REVIEW

**Comment by adamdom** [comment]
LGTM. Can you also include on this branch updated alumni?

**Comment by adamdom** [comment]
LGTM.

**Comment by adelq** [comment]
Year updates LGTM
I've got a couple of observations about the alumni updates:
1. You've missed a couple Labs alumni that just graduated: Alex Wissman and Hong Kim
2. Inconsistent "graduation" to alumni status: to date, you became an alumni on the website when you graduate, so Hong is alumni but Derek is not. I noticed you moved David and Prakhar to the alumni list though, so either add the rest of the Labs alumni that haven't graduated (Derek, Jake, ...?) or take Prakhar and David off for now.

Of course, these are very nitpicky and can be done in another pull request, but ideally should be fixed before recruitment begins again.

**Comment by jasontsh** [comment]
Adam has looked at it and says LGTM

**Pull request merged**
