### PR TITLE
Bios

### PR DESCRIPTION
**Pull request by younglee327**
Made biographies easier to edit and add (see Readme file in _data folder) using the Liquid templating engine. This will make adding new members and removing old ones super easy!

### CODE REVIEW

**Comment by adelq** [comment]
This is amazing! Let me take a look at it, seems like the logo change commit snuck in here but not a problem since it's already been merged.

**Comment by younglee327** [comment]
Also side note: I replace the first occurrence of the name with the link to their website (i.e. the hacky part) so that it'd be easier for someone submitting their bio to not worry about having it link to anything!

**Comment by younglee327** [comment]
Readme update commit adds instructions for alum-bios.yml and examples for both.

**Comment by adelq** [comment]
LGTM

**Pull request merged**
